from model.coordinate import Coordinate

# 720p

MAP_TOP_LEFT = Coordinate(100, 210)
MAP_BOTTOM_RIGHT = Coordinate(860, 700)

ARROW_TOP_LEFT_X = 105
ARROW_TOP_LEFT_Y = 185
ARROW_BOTTOM_RIGHT_X = 130
ARROW_BOTTOM_RIGHT_Y = 210
ARROW_BBOX = (ARROW_TOP_LEFT_X, ARROW_TOP_LEFT_Y, ARROW_BOTTOM_RIGHT_X, ARROW_BOTTOM_RIGHT_Y)

PIXELS_PER_SECOND = 15